# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aa100fcd1157a4f27a51a763b0b40a4caed8733bb0a47e5a1eb18360aa093a339c311d71e284fcfac54927aeafe8c23849fbcc4b4ae0eadc5c79fe682751fdb

test:
  secret_key_base: 6b446683a34027814695ac20fc702bb90d57275638047654e712183eab2672cc1ca371bc8c5cf73dcc549839ef8949a0755f8d0d713fa1e1d06085823bc23401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
